version: '3.7'
services:
  emsci:
    build:
        target: build-stage
        context: .
    environment:
      - DOCKER_HOST=tcp://docker:2375
    volumes:
      - .:/app
    environment:
      - GO111MODULE=on
    depends_on:
      - docker
    command: /bin/bash
    working_dir: /app
  docker:
    image: docker:stable-dind
    privileged: true
    command: dockerd --host 0.0.0.0:2375
